auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            LiuMian
url:              http://liumian.github.io
author:
    name:         LiuMian
description:      "LiuMian\'s Blog"
author_info:      <a href="http://liumian.github.io/about">LiuMian</a>

copyright:
    - Design by <a href="http://liumian.github.io/about" title="LiuMian" target="_blank">LiuMian</a> &copy; 2014
